### ISSUE TITLE
Idea?

### ISSUE THREAD

**Issue by Sellto** [RikardoPons/UniversalFormsToolkit#2]
Hello, 
I use your Autogenerate Property in my App ... 
And I use a ObservableCollection</T/> where the T has some [AutoGenerateProperty] (a string and a boolean) ... 

This ObservableCollection is used in a Stackpanel but the autogeneratedproperty doesn't appear... 
and when I put the  [AutoGenerateProperty] on the Collection a i have Dropdown list 

Idea?

**Comment by RickPons** [comment]
Hello! ObservableCollection is a collection of items The autogenerator will draw a ComboBox to select some item.
Please download the examples to see how ObservableCollection is working with the AutoGenerator.

**Comment by Sellto** [comment]
Ok i have found a solution :)
