### ISSUE TITLE
AutoGenerate With TimeSpan

### ISSUE THREAD

**Issue by Sellto** [RikardoPons/UniversalFormsToolkit#3]
Just for information,
 
When i use AutoGenerateProperty into TimeSpan Property i get a DatePicker and not a TimePicker.

all the best

TS.

**Comment by RickPons** [comment]
I will check it! Thank you!

**Comment by RickPons** [comment]
Now is fixed I will update the nuget package today

**Comment by Sellto** [comment]
Hi!
Nice Job, I have a TimePicker with a TimeSpan Property.
but now, when I choose an other element in the Listview, my App Crash.
(if I remove the AutogenerateProperty on the TimeSpan , no crash...)

All the best.

TS.

**Comment by RickPons** [comment]
@Sellto  Do you have an example? I can not reproduce this issue.
